---

- name: Ensure hostname is resolvable
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"

- name: Ensure go group
  sudo: yes
  group:
    name: "{{ gocd_server.group }}"
    state: present

- name: Ensure go user
  sudo: yes
  user:
    name: "{{ gocd_server.user }}"
    comment: Go CD User
    group: "{{ gocd_server.group }}"
    home: "{{ gocd_server.user_dir }}"

- name: Install some dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - tree

- name: add GO CD apt repository
  sudo: yes
  apt_repository:
    repo: deb http://dl.bintray.com/gocd/gocd-deb/ /
    state: present

- name: Install go-server
  sudo: yes
  apt:
    name: "go-server={{ gocd_server.version }}"
    state: present
    force: yes

- name: Add go-server to autostart
  sudo: yes
  service:
    name: go-server
    enabled: yes
    state: stopped
