---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"

- name: Install some dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ gocd_server.packages }}"

- name: add GO CD apt repository
  become: yes
  apt_repository:
    repo: deb http://dl.bintray.com/gocd/gocd-deb/ /
    state: present

- name: Install go-server
  become: yes
  apt:
    name: "go-server={{ gocd_server.version }}"
    state: present
    force: yes

- name: Install AWS CLI
  become: yes
  pip:
    name: "{{ item }}"
  when: gocd_server.aws.backup_bucket
  with_items:
    - awscli
    - boto

- name: Add go-server to autostart
  become: yes
  service:
    name: go-server
    enabled: yes
    state: stopped
