---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost {{ ansible_hostname }}"
    regexp: ^127\.0\.0\.1

- name: Install some dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ gocd_server.packages }}"
  
- name: Install AWS CLI
  become: yes
  pip:
    name: "{{ item }}"
  when: gocd_server.aws.install_cli
  with_items:
    - awscli
    - boto

- name: add GO CD apt repository
  become: yes
  apt_repository:
    repo: deb http://dl.bintray.com/gocd/gocd-deb/ /
    state: present

- name: Install go-server
  become: yes
  apt:
    name: "go-server={{ gocd_server.version }}"
    state: present
    force: yes

- name: Create various directories
  become: yes
  file:
    group: "{{ gocd_server.group }}"
    owner: "{{ gocd_server.user }}"
    path: "/home/{{ gocd_server.user }}/{{ item }}"
    state: directory
  with_items:
    - work/go-server
    - bin
    - .aws

- name: Add go-server to autostart
  become: yes
  service:
    name: go-server
    enabled: yes
    state: stopped
